# This file should only be edited from the template
name: Classroom Repo Init from Template

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/template.yml

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  checks: write
  actions: read
  contents: read
  issues: write

jobs:
  build:
    name: "Copy Issues from Template"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: .github/template/cpissues.sh
      - run: gh issue list -s all 

